[project]
name = "stellarvista"
description = "3D visualizations for OpenMC"
version = "0.0.1"

readme = "README.md"
requires-python = ">=3.12.0"
authors = [
    {name = "Sam Pasmann", email = "sam.pasmann@thea.energy"},
]

keywords = ["stellarator", "tokamak", "fusion", "openmc", "cad",
            "model", "dagmc", "visualization"]
license = {file="LICENSE.md"}
classifiers = [
       "Development Status :: 3 - Alpha",
       "Intended Audience :: Science/Research",
       "Intended Audience :: Developers",
       "License :: OSI Approved :: MIT License",
       "Natural Language :: English",
       "Operating System :: OS Independent",
       "Topic :: Scientific/Engineering :: Physics",
       "Topic :: Scientific/Engineering",
       "Topic :: Scientific/Engineering :: Human Machine Interfaces",
       "Programming Language :: Python :: 3 :: Only",
       "Programming Language :: Python :: 3.11",
]

# TODO: add PyMOAB once on PyPI
dependencies = [
    "pydagmc",
    "pyvista[all]",
    "pandas",
    "numpy",
    "openmc",
    "setuptools==80.8.0",
]

[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools]
packages = ["stellarvista"]

[tool.pyright]
include = ["stellarvista"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.12"