[project]
name = "stellarvista"
description = "3D visualizations for DAGMC & OpenMC"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12.0"
authors = [
    {name = "Sam Pasmann"},
]

keywords = ["stellarator", "tokamak", "fusion", "openmc", "cad",
            "model", "dagmc", "visualization"]
license = {file="LICENSE.md"}

dependencies = [
    "pyvista[all]",
    "dagmc-h5m-file-inspector",
    "pandas<3.0", # waiting for version of OpenMC with PR 3743 to be released
    "numpy",
    "openmc>=0.15.3",
    "vtk",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.12.8",
]

[tool.ruff]
target-version = "py312"
exclude = ["examples/"]

[tool.ruff.lint]
extend-select = [
  "D103",  # undocumented public function
]
pydocstyle.convention = "google"

[tool.pyright]
include = ["stellarvista"]
reportMissingImports = true
reportMissingTypeStubs = false
pythonVersion = "3.12"
